name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5' # Change to your Go version

      - name: Check Go formatting
        run: |
          fmt_output=$(go fmt ./...)
          if [ -n "$fmt_output" ]; then
            echo "The following files are not properly formatted:"
            echo "$fmt_output"
            echo "Run 'go fmt ./...' locally to fix."
            exit 1
          fi

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./... -v
